# Generated by Django 3.2.4 on 2022-01-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='blog_img')),
                ('date', models.DateTimeField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('additional_point', models.TextField(max_length=80)),
                ('details', models.TextField(default='InDetail', max_length=900000)),
            ],
        ),
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('Msg', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='main_page_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
