# Generated by Django 3.2.4 on 2022-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_author', models.CharField(max_length=15)),
                ('lat_img', models.ImageField(upload_to='blog_img')),
                ('lat_date', models.DateTimeField()),
                ('lat_view', models.PositiveIntegerField(default=0)),
                ('lat_additional_point', models.TextField(max_length=80)),
                ('lat_details', models.TextField(default='Latest', max_length=900000)),
            ],
        ),
    ]
