# Generated by Django 3.2.4 on 2022-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sli_first', models.ImageField(upload_to='slider_img')),
                ('first_additional_point', models.TextField(max_length=80)),
                ('first_detail', models.TextField(default='First Slider', max_length=900000)),
                ('sli_second', models.ImageField(upload_to='slider_img')),
                ('second_additional_point', models.TextField(max_length=80)),
                ('second_detail', models.TextField(default='Second Slider', max_length=900000)),
                ('sli_third', models.ImageField(upload_to='slider_img')),
                ('third_additional_point', models.TextField(max_length=80)),
                ('third_detail', models.TextField(default='Third Slider', max_length=900000)),
            ],
        ),
    ]
